# Generated by Django 4.1.6 on 2023-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orderplaced_ordered_date_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'Vegetable'), ('F', 'Fruits'), ('TV', 'TopVegetable'), ('BV', 'BottomVegetable')], max_length=2),
        ),
    ]
